//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.05.09 at 01:17:02 PM IST 
//


package com.uniper.tableau.bindings;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for siteRoleType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="siteRoleType"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="Guest"/&gt;
 *     &lt;enumeration value="Interactor"/&gt;
 *     &lt;enumeration value="Publisher"/&gt;
 *     &lt;enumeration value="ServerAdministrator"/&gt;
 *     &lt;enumeration value="SiteAdministrator"/&gt;
 *     &lt;enumeration value="Unlicensed"/&gt;
 *     &lt;enumeration value="UnlicensedWithPublish"/&gt;
 *     &lt;enumeration value="Viewer"/&gt;
 *     &lt;enumeration value="ViewerWithPublish"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "siteRoleType")
@XmlEnum
public enum SiteRoleType {

    @XmlEnumValue("Guest")
    GUEST("Guest"),
    @XmlEnumValue("Interactor")
    INTERACTOR("Interactor"),
    @XmlEnumValue("Publisher")
    PUBLISHER("Publisher"),
    @XmlEnumValue("ServerAdministrator")
    SERVER_ADMINISTRATOR("ServerAdministrator"),
    @XmlEnumValue("SiteAdministrator")
    SITE_ADMINISTRATOR("SiteAdministrator"),
    @XmlEnumValue("Unlicensed")
    UNLICENSED("Unlicensed"),
    @XmlEnumValue("UnlicensedWithPublish")
    UNLICENSED_WITH_PUBLISH("UnlicensedWithPublish"),
    @XmlEnumValue("Viewer")
    VIEWER("Viewer"),
    @XmlEnumValue("ViewerWithPublish")
    VIEWER_WITH_PUBLISH("ViewerWithPublish");
    private final String value;

    SiteRoleType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static SiteRoleType fromValue(String v) {
        for (SiteRoleType c: SiteRoleType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
